name: dokku-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: alpine-latest
    steps:
      - name: dokku
        uses: dokku/github-action@v1.4.0
        with:
          branch: main
          command: deploy
          git_remote_url: dokku@dokku.mpbuyanov.ru:dick
          ssh_private_key: ${DOKKU_PRIVATE_KEY}
